### ISSUE TITLE
Imprint text not displaying

### ISSUE THREAD

**Issue by nerdusMaximus** [codevise/pageflow#1207] opened 2019-08-29 10:20 UTC
Hello Pageflow team,

I have an issue with the imprint label not being displayed in my pageflow stories.
The Imprint link label and imprint link URL is set in the account settings but there is nothing displayed. There is a clickable link tag but only the gray background is displayed.

For testing purposes, I added credits to see if those will be displayed. They are not as well. The clickable area is bigger on the gray background but still nothing displayed.

I hofe you can help me on this one. I checked the prod log but the file is clear.

**Comment by tf** [comment] 2019-08-29 12:03
Duplicate of #1208.

**Closed by tf** 2019-08-29 12:03 UTC
