### ISSUE TITLE
Cant upload images

### ISSUE THREAD

**Issue by Gutz-Pilz** [codevise/pageflow#315] opened 2015-06-26 12:31 UTC
Hi there,

i got the server runninfg and can edit text and so on.
when i try to visit through the given permalink (http://localhost:3000/example-entry) it says:
The page you were looking for doesn't exist.

also i cant add images and videos
how can i run backgroundworker properly?
if i execute the command from the readme - it giyes warning and trap6

**Comment by tf** [comment] 2015-06-26 12:40
Hi,

did you publish the entry via the editor before visiting the permalink?

Could you paste the output of running `QUEUE=* bundle exec rake resque:work`.

**Comment by Gutz-Pilz** [comment] 2015-06-26 12:54
```
Hannes$ QUEUE=* rake resque:work
WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
/Users/Hannes/.rvm/gems/ruby-2.1.0@rails-4.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:129: [BUG] rb_sys_fail_str(connect(2) for [fe80::1%lo0]:6379) - errno == 0
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin14.0]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.

.....
.....

.....
[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
```

**Comment by Gutz-Pilz** [comment] 2015-06-26 13:03
found the public button ;)
sorry for that

```QUEUE=* bundle exec rake resque:work```

gives the same errors
maybe it has to do with the '*' again

**Comment by tf** [comment] 2015-06-26 13:04
Could be a Ruby 2.1 problem. Could be Ruby problem on your machine.

In the last issue, you used Ruby 1.9.3 to run setup your app. 

* Does it give the same error when you use Ruby 1.9.3?
* Does a simple `rake -T` work?

**Comment by Gutz-Pilz** [comment] 2015-06-27 08:22
Tried with 1.9.3

```Hannes_mac:my_pageflow-test Hannes$ ruby -v
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin14.3.0]
Hannes_mac:my_pageflow-test Hannes$ QUEUE=* rake resque:work
WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
rake aborted!
Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (ECONNREFUSED)
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis/client.rb:290:in `rescue in establish_connection'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis.rb:784:in `block in get'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-3.0.7/lib/redis.rb:783:in `get'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:393:in `call_with_namespace'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:290:in `method_missing'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/resque-1.25.2/lib/resque/worker.rb:617:in `job'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/resque-1.25.2/lib/resque/worker.rb:546:in `unregister_worker'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/resque-1.25.2/lib/resque/worker.rb:215:in `rescue in work'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/resque-1.25.2/lib/resque/worker.rb:162:in `work'
/Users/Hannes/.rvm/gems/ruby-1.9.3-p551/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'
Tasks: TOP => resque:work
(See full trace by running task with --trace)```

**Comment by Gutz-Pilz** [comment] 2015-06-27 08:55
ok. worker and scheduler now running.
had to reinstall redis with brew

But i am still not able to upload images

**Comment by tf** [comment] 2015-06-27 11:46
Since these things come up over and over again, I've begun extending the [Trouble Shooting wiki page](https://github.com/codevise/pageflow/wiki/Troubleshooting). For now I only added notes about the log files that need be consulted to diagnose the error. We can then start collecting concrete exception messages from the log files and add solutions to the wiki page.

**Comment by tf** [comment] 2015-07-03 06:51
Any update here?

**Comment by Gutz-Pilz** [comment] 2015-07-03 06:55
dont have a amazonaws s3 account.
is there a way to use pageflow without amazon ?

**Comment by tf** [comment] 2015-07-03 06:58
At the moment, no. See also #54.

**Comment by tf** [comment] 2015-07-06 09:23
So if the error was caused by a missing Amazon configuration, I'll close this issue, ok?

**Comment by Gutz-Pilz** [comment] 2015-07-06 09:25
yes. thats fine!

**Closed** 2015-07-06 09:25 UTC

**Comment by din0715** [comment] 2019-02-27 03:24
I set config data in initializer/pageflow.rb, but I can not upload images to s3.
When clicking upload button, jquery_file_upload url is localhost:3000/editor/entries/1/files/image_files.

Already, I execute the commands in the guide.

**Comment by tf** [comment] 2019-02-27 08:26
Please open a new issue instead of commenting on a closed one. Please include a link to a gist containing your `Gemfile`, `Gemfile.lock`, `config/initializers/pageflow.rb` and an excerpt of your log file  (`log/development.log` or `log/production.log` depending on the environment you are running in) that includes the failed upload request.
